### ISSUE TITLE
emit not working - not emiting to all clients and Random is not defined.

### ISSUE THREAD

**Issue by ghost** [arunoda/meteor-streams#40]
Just in stalled Streams and added the standard example code (with correct permissions)

chatStream = new Meteor.Stream('chat');

sendChat = function(message) {
    chatStream.emit('message', message);
    console.log('me: ' + message);
};

chatStream.on('message', function(message, arg) {
    console.log(arg);
    console.log('user: ' + message);
});

I run into the following two errors:
1. When I load my Meteor app for the first time I get the following exception:
   I20151005-11:50:11.732(1)? Exception from sub stream-chat id S6sjbJYZ3zn4wLr8f ReferenceError: Random is not defined
   I20151005-11:50:11.734(1)?     at [object Object]._handler (packages/streams/lib/server.js:40:1)
   I20151005-11:50:11.734(1)?     at maybeAuditArgumentChecks (livedata_server.js:1692:12)
   I20151005-11:50:11.734(1)?     at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
   I20151005-11:50:11.734(1)?     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
   I20151005-11:50:11.734(1)?     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
   I20151005-11:50:11.734(1)?     at livedata_server.js:548:43
   I20151005-11:50:13.321(1)? Exception from sub stream-chat id 7bv8NZNAp7pP9KT8G ReferenceError: Random is not defined
   I20151005-11:50:13.321(1)?     at [object Object]._handler (packages/streams/lib/server.js:40:1)
   I20151005-11:50:13.321(1)?     at maybeAuditArgumentChecks (livedata_server.js:1692:12)
   I20151005-11:50:13.321(1)?     at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
   I20151005-11:50:13.321(1)?     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
   I20151005-11:50:13.321(1)?     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
   I20151005-11:50:13.322(1)?     at livedata_server.js:548:43
2. Events are not emitted to all clients, only the sender.

**Comment by team-pie** [comment]
has this been fixed? I'm having a similar issue

**Comment by kusmierz** [comment]
Try add to your app package [Random](https://atmospherejs.com/meteor/random):

``` bash
meteor add random
```

**Comment by team-pie** [comment]
Yeah I did that. Thanks. Would be nice to include it in the dependencies

**Comment by kusmierz** [comment]
@papero-co I think so too, but unfortunately it seems the project is no longer maintained :( see #21

**Comment by team-pie** [comment]
I've seen that. I could not tell if @lepozepo had taken over. Anyway problem fixed for me :)
