### ISSUE TITLE
Your app is crashing. Here's the latest log.

### ISSUE THREAD

**Issue by mspkom** [arunoda/meteor-streams#41]
Homepage-Example: Your app is crashing. Here's the latest log.

/Applications/MAMP/htdocs/frequentis/ms-homepage/.meteor/local/build/server/server.js:337
  }).run();
     ^
TypeError: undefined is not a function
    at app/server-to-client.js:1:32
    at /Applications/MAMP/htdocs/frequentis/ms-homepage/.meteor/local/build/server/server.js:298:12
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/manfredspecht/.meteor/tools/cc18dfef9e/lib/node_modules/underscore/underscore.js:78:11)
    at run (/Applications/MAMP/htdocs/frequentis/ms-homepage/.meteor/local/build/server/server.js:239:7)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.

**Comment by ghost** [comment]
I have the same issue please can someone answer
